# Generated by Django 2.1.7 on 2019-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_auto_20190220_1253'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='selectedCourses',
            field=models.ManyToManyField(blank=True, to='Courses.Course'),
        ),
    ]
