# Generated by Django 2.1.7 on 2019-05-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_auto_20190220_1253'),
        ('login', '0002_registereduser_selectedcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='takenCourses',
            field=models.ManyToManyField(blank=True, related_name='takenCourses', to='Courses.Course'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='selectedCourses',
            field=models.ManyToManyField(blank=True, related_name='selectedCourses', to='Courses.Course'),
        ),
    ]
