# Generated by Django 2.1.7 on 2019-02-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_day_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='days',
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='Courses.Day'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='slots',
        ),
        migrations.AddField(
            model_name='course',
            name='slots',
            field=models.ManyToManyField(blank=True, null=True, to='Courses.Slot'),
        ),
    ]
