# Generated by Django 2.1.7 on 2019-02-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_auto_20190218_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='days',
            field=models.ManyToManyField(blank=True, to='Courses.Day'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slots',
            field=models.ManyToManyField(blank=True, to='Courses.Slot'),
        ),
    ]
