# Generated by Django 2.1.7 on 2019-02-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slots',
        ),
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.ManyToManyField(blank=True, to='Courses.Hours'),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
